<a href="https://colab.research.google.com/github/Cyber-Hash-pro/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [7]:
arr=[[1,2,3],[2,3,5],[5,3,5]]
np.array(arr)

array([[1, 2, 3],
       [2, 3, 5],
       [5, 3, 5]])

In [11]:
arrray=np.arange(1,11,2)
arrray

array([1, 3, 5, 7, 9])

In [ ]:
zero=np.zeros((3,4))

In [ ]:
one=np.zeros((3,4))

In [16]:
arraya=np.linspace(1,3,5)
# first value deside stat seocnd value stop and kitne chiye third and that have linsspace same gap hoga
arraya

array([1. , 1.5, 2. , 2.5, 3. ])

In [17]:
np.random.rand(10)
# concpt to standationzation
#vectore answer
# normalization 0 to 1
# standationzation -3 to 3

array([0.85543257, 0.3688435 , 0.06138067, 0.45832844, 0.2487693 ,
       0.83520383, 0.69482815, 0.37435959, 0.86566055, 0.89454237])

In [19]:
np.random.randint(6)
# o se 6 kuch bhi number gerate karta he
np.random.randint(10,20,10)

array([10, 15, 10, 16, 18, 18, 12, 17, 12, 19])