<a href="https://colab.research.google.com/github/Cyber-Hash-pro/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [30]:
arr=[[1,2,3],[2,3,5],[5,3,5]]
np.array(arr)

array([[1, 2, 3],
       [2, 3, 5],
       [5, 3, 5]])

In [31]:
arrray=np.arange(1,11,2)
arrray
#np.arange(start, stop, step) ek range ke numbers ka NumPy array banata hai.

array([1, 3, 5, 7, 9])

In [32]:
zero=np.zeros((3,4))

In [33]:
one=np.zeros((3,4))

In [34]:
arraya=np.linspace(1,3,5)
# first value deside stat seocnd value stop and kitne chiye third and that have linsspace same gap hoga
arraya

array([1. , 1.5, 2. , 2.5, 3. ])

In [35]:
np.random.rand(10)
# concpt to standationzation
#vectore answer
# normalization 0 to 1
# standationzation -3 to 3

array([0.27116449, 0.45634551, 0.69937513, 0.2324324 , 0.8925055 ,
       0.72346982, 0.64214685, 0.87837462, 0.99681431, 0.91833699])

In [36]:
np.random.randint(6)
# o se 6 kuch bhi number gerate karta he
np.random.randint(10,20,10)

array([17, 16, 12, 19, 12, 10, 15, 17, 11, 16])

In [37]:
arr=np.array([[1,2,3],[3,4,5],[5,6,7]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [38]:
arr.size

9

In [39]:
arr.shape

(3, 3)

In [40]:
arr.dtype
#atritubde () nahi lagte hae ham

dtype('int64')

In [41]:
arr.min()
arr.max()


np.int64(7)

In [42]:
arr.sum()

np.int64(36)

In [43]:
np.sum(arr,axis=0)
# is flow the axis ---|--> 1  ek x-axis 1 and y axis 0

array([ 9, 12, 15])

In [45]:
arr.mean()


np.float64(4.0)

In [48]:
np.mean(arr, axis=1)

array([2., 4., 6.])

In [49]:
arr.std()
# Standard Deviation

np.float64(1.8257418583505538)

In [51]:
arr.argmax()
# max element ka index in array
arr.argmin()

np.int64(8)

In [54]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [59]:
arr.reshape(6,5)
# 6*5=30 element
# when you are reshpan to dya krna ki to apke element cout same hoan chaiye
# agar nahi hova to erro ris
# ValueError: cannot reshape array of size 30 into shape (6,6)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])